### ISSUE TITLE
make browserifiable?

### ISSUE THREAD

**Issue by sbma44** [bbc/slayer#2]
Hi there! Thanks a ton for writing this module, you saved me a bunch of time. I had to make a couple of minor adjustments to get it working in the browser, which I did in a fork. Specifically removing runtime plugin system for algorithms. The algorithm files seem pretty lightweight -- would you consider simply baking them all into the module? If so I'd be happy to make a PR.

Let me also ask: is there any reason to make the interface asynchronous?

**Comment by thom4parisot** [comment]
Hi there :-)

Yes sure having it browserifiable would be ace! I'll happily review your PR.

Re the no-being-asynchronous part: as all the operations are based on array loops, I did not feel the need to make the interface asynchronous — all the processing is synchronous.

The streaming interface would logically be asynchronous.

Do you see a case for asynchronicity otherwise?

**Comment by sbma44** [comment]
Great. I need to wrap up the presentation I've been using it to prepare for but will try to get you a PR thereafter.

I may have been unclear in OP: right now the interface to `.fromArray(data, onComplete)` strikes me as being async. I'd personally prefer that it be synchronous (it's easier to go from sync to async, after all, when you do have some I/O operation like the streaming interface you mention).

**Comment by thom4parisot** [comment]
Aah I get it. I forgot about this method signature.

I wrote it like to be eventually async in the future but even though this is a callback, the processing is synchronous. Maybe it is ambiguous and should return the value directly.

Have a look as [this segment of the source code](https://github.com/bbcrd/slayer/blob/2a91d7f5a44f78aac8d0ff5abbddac111df0114c/lib/readers/array.js#L73-L80) to clear your doubts about async processing.

**Comment by thom4parisot** [comment]
By the way, I filled another issue (#5) to return a promise of passing the data to a callback.

**Comment by thom4parisot** [comment]
Hi @sbma44!

`slayer@1.0.0` is now on npm and now contains changes which will make your life easier:
1. `fromArray` returns a Promise instead of using a callback – #5
2. there is no more `require` in the `.use()` method – #7 
3. plus there is now a streaming detection too – #4 

Feel free to tell me how it goes in term of browserification, and if there is anything which should be changed to make it even easier to embed it in the browser.

**Comment by sbma44** [comment]
Awesome @oncletom. My presentation got bumped so I'm likely to pick this back up later in the year. I really appreciate the changes! Will check back in then.

**Comment by thom4parisot** [comment]
@sbma44 sure!

In the meantime I tried https://runkit.com/5800fd882bfbec0014aee45c/5800fd882bfbec0014aee45d and confirm it works with browserify :-) Same results with requirebin.com!

Let me know if there is anything else which could be helpful.

Thanks for the heads-up and out of curiosity, do you use for your personal use or at MapBox?

Cheers :-)

**Comment by sbma44** [comment]
Personal use! Giving a talk about an ultrasonic distance sensor I built for my bike to measure how much space cars give me when they pass. I used Slayer to smooth the data.
